[package]
name = "robocrafterlp/cmdrplus"
description = "Extensible command console for Roblox developers with a cmd menu"
version = "1.1.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
include = ["src", "src/*", "wally.toml", "default.project.json", "sourcemap.json", "selene.toml"]

[dependencies]
Networker = "leifstout/networker@0.3.0"
Sift = "csqrl/sift@0.0.11"