[package]
name = "robocrafterlp/cmdrplus"
description = "Extensible command console for Roblox developers"
version = "1.0.1"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"
exclude = ["assets", "docs","sourcemap.json"]
include = ["CmdrPlus", "default.project.json", "LICENSE"]

[dependencies]
