[package]
name = "robocrafterlp/cmdrplus"
description = "Extensible command console for Roblox developers with a cmd menu"
version = "1.0.8"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["assets", "docs","sourcemap.json", "node_modules", ".github", "moonwave.toml", "package-lock.json", "package.json"]
include = ["CmdrPlus", "default.project.json", "LICENSE"]

[dependencies]
