return function(Parent)
    local Cmd = Instance.new("Frame")
	Cmd.Name = "Cmd"
	Cmd.Parent = Parent
	-- Cmd.AnchorPoint = Vector2.new(0.5, 0.5)
	Cmd.BackgroundColor3 = Color3.fromRGB(17, 17, 17)
	Cmd.BackgroundTransparency = 0.400
	Cmd.BorderColor3 = Color3.fromRGB(0, 0, 0)
	Cmd.BorderSizePixel = 0
	Cmd.Position = UDim2.new(0.15, 0, 0.15, 0)
    Cmd.Size = UDim2.new(0.7, 0, 0.7, 0)
	Cmd.Visible = false

	local Header = Instance.new("Frame")
	Header.Name = "Header"
	Header.Parent = Cmd
	Header.Active = true
	Header.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	Header.BackgroundTransparency = 1.000
	Header.BorderColor3 = Color3.fromRGB(0, 0, 0)
	Header.BorderSizePixel = 0
    Header.Size = UDim2.new(1, 0, 0.075000003, 0)

	local Close = Instance.new("TextButton")
	Close.Name = "Close"
	Close.Parent = Header
	Close.AnchorPoint = Vector2.new(1, 0)
	Close.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	Close.BackgroundTransparency = 1.000
	Close.BorderColor3 = Color3.fromRGB(0, 0, 0)
	Close.BorderSizePixel = 0
	Close.Position = UDim2.new(1, 0, 0, 0)
	Close.Size = UDim2.new(0.899999976, 0, 0.899999976, 0)
	Close.Font = Enum.Font.Code
	Close.Text = "X"
	Close.TextColor3 = Color3.fromRGB(255, 255, 255)
	Close.TextScaled = true
	Close.TextSize = 14.000
    Close.TextWrapped = true

	local UIAspectRatioConstraint = Instance.new("UIAspectRatioConstraint")
    UIAspectRatioConstraint.Parent = Close

	local TextLabel = Instance.new("TextLabel")
	TextLabel.Parent = Header
	TextLabel.AnchorPoint = Vector2.new(0, 0.5)
	TextLabel.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	TextLabel.BackgroundTransparency = 1.000
	TextLabel.BorderColor3 = Color3.fromRGB(0, 0, 0)
	TextLabel.BorderSizePixel = 0
	TextLabel.Position = UDim2.new(0, 0, 0.5, 0)
	TextLabel.Size = UDim2.new(1, 0, 0.800000012, 0)
	TextLabel.Font = Enum.Font.Code
	TextLabel.Text = "Cmdr Plus Commnad Runner"
	TextLabel.TextColor3 = Color3.fromRGB(255, 255, 255)
	TextLabel.TextScaled = true
	TextLabel.TextSize = 14.000
	TextLabel.TextWrapped = true

	local Sep = Instance.new("Frame")
	Sep.Name = "Sep"
	Sep.Parent = Header
	Sep.AnchorPoint = Vector2.new(0, 1)
	Sep.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	Sep.BorderColor3 = Color3.fromRGB(0, 0, 0)
	Sep.BorderSizePixel = 0
	Sep.Position = UDim2.new(0, 0, 1, 0)
	Sep.BorderSizePixel = 0
	Sep.Size = UDim2.new(1, 0, 0.0529100522, 0)

	local CmdList = Instance.new("ScrollingFrame")
	CmdList.Name = "CmdList"
	CmdList.AutomaticCanvasSize = Enum.AutomaticSize.Y
	CmdList.Parent = Cmd
	CmdList.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	CmdList.BackgroundTransparency = 1.000
	CmdList.BorderColor3 = Color3.fromRGB(0, 0, 0)
	CmdList.BorderSizePixel = 0
	CmdList.Position = UDim2.new(0, 0, 0.075000003, 0)
	CmdList.Selectable = false
	CmdList.Size = UDim2.new(0.300000012, 0, 0.925000012, 0)
	CmdList.CanvasSize = UDim2.new(0, 0, 0, 0)
	CmdList.ScrollBarThickness = 6
	CmdList.HorizontalScrollBarInset = Enum.ScrollBarInset.None

	local UIListLayout = Instance.new("UIListLayout")
	UIListLayout.Parent = CmdList
	UIListLayout.SortOrder = Enum.SortOrder.LayoutOrder

	local HeaderSample = Instance.new("Frame")
	HeaderSample.Name = "HeaderSample"
	HeaderSample.Parent = CmdList
	HeaderSample.BackgroundColor3 = Color3.fromRGB(50, 50, 50)
	HeaderSample.BackgroundTransparency = 0.400
	HeaderSample.BorderColor3 = Color3.fromRGB(0, 0, 0)
	HeaderSample.BorderSizePixel = 0
	HeaderSample.Size = UDim2.new(1, 0, 0.075000003, 0)
	HeaderSample.Visible = false

	local Label = Instance.new("TextLabel")
	Label.Name = "Label"
	Label.Parent = HeaderSample
	Label.AnchorPoint = Vector2.new(1, 0.5)
	Label.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	Label.BackgroundTransparency = 1.000
	Label.BorderColor3 = Color3.fromRGB(0, 0, 0)
	Label.BorderSizePixel = 0
	Label.Position = UDim2.new(1, 0, 0.5, 0)
	Label.Size = UDim2.new(0.949999988, 0, 0.800000012, 0)
	Label.Font = Enum.Font.Code
	Label.TextColor3 = Color3.fromRGB(255, 255, 255)
	Label.TextScaled = true
	Label.TextSize = 14.000
	Label.TextWrapped = true
	Label.TextXAlignment = Enum.TextXAlignment.Left

	local spacex = (1 - Label.Size.X.Scale)
	local Sep4 = Instance.new("Frame")
	Sep4.AnchorPoint = Vector2.new(1, .5)
	Sep4.Name = "Sep"
	Sep4.Parent = Label
	Sep4.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	Sep4.BorderColor3 = Color3.fromRGB(0, 0, 0)
	Sep4.BorderSizePixel = 0
	Sep4.Position = UDim2.new(1, 0, 1, 0)
	Sep4.BorderSizePixel = 0
	Sep4.Size = UDim2.new(1 + spacex, 0, .075, 0)

	local CmdSample = Instance.new("ImageButton")
	CmdSample.Name = "CmdSample"
	CmdSample.Parent = CmdList
	CmdSample.Active = false
	CmdSample.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
	CmdSample.BackgroundTransparency = 0.400
	CmdSample.BorderColor3 = Color3.fromRGB(0, 0, 0)
	CmdSample.BorderSizePixel = 0
	CmdSample.Selectable = false
	CmdSample.Size = UDim2.new(1, 0, 0.075000003, 0)
	CmdSample.Visible = false

	local Label2 = Instance.new("TextLabel")
	Label2.Name = "Label"
	Label2.Parent = CmdSample
	Label2.AnchorPoint = Vector2.new(1, 0.5)
	Label2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	Label2.BackgroundTransparency = 1.000
	Label2.BorderColor3 = Color3.fromRGB(0, 0, 0)
	Label2.BorderSizePixel = 0
	Label2.Position = UDim2.new(1, 0, 0.5, 0)
	Label2.Size = UDim2.new(0.899999976, 0, 0.699999988, 0)
	Label2.Font = Enum.Font.Code
	Label2.TextColor3 = Color3.fromRGB(255, 255, 255)
	Label2.TextScaled = true
	Label2.TextSize = 14.000
	Label2.TextWrapped = true
	Label2.TextXAlignment = Enum.TextXAlignment.Left

	local Content = Instance.new("Frame")
	Content.Name = "Content"
	Content.Parent = Cmd
	Content.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	Content.BackgroundTransparency = 1.000
	Content.BorderColor3 = Color3.fromRGB(0, 0, 0)
	Content.BorderSizePixel = 0
	Content.Position = UDim2.new(0.300000012, 0, 0.075000003, 0)
	Content.Size = UDim2.new(0.699999988, 0, 0.925000012, 0)

	local Buttons = Instance.new("Frame")
	Buttons.Name = "Buttons"
	Buttons.Parent = Content
	Buttons.AnchorPoint = Vector2.new(0, 1)
	Buttons.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	Buttons.BackgroundTransparency = 1.000
	Buttons.BorderColor3 = Color3.fromRGB(0, 0, 0)
	Buttons.BorderSizePixel = 0
	Buttons.Position = UDim2.new(0, 0, 1, 0)
	Buttons.Size = UDim2.new(1, 0, 0.100000001, 0)

	local Sep2 = Instance.new("Frame")
	Sep2.Name = "Sep"
	Sep2.Parent = Buttons
	Sep2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	Sep2.BorderColor3 = Color3.fromRGB(0, 0, 0)
	Sep2.BorderSizePixel = 0
	Sep2.Size = UDim2.new(1, 0, 0.0429000445, 0)
	Sep2.BorderSizePixel = 0

	local Close2 = Instance.new("TextButton")
	Close2.Name = "Close"
	Close2.Parent = Buttons
	Close2.AnchorPoint = Vector2.new(1, 0)
	Close2.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
	Close2.BackgroundTransparency = 0.900
	Close2.BorderColor3 = Color3.fromRGB(0, 0, 0)
	Close2.BorderSizePixel = 0
	Close2.Position = UDim2.new(1, 0, 0, 0)
	Close2.Size = UDim2.new(1, 0, 1, 0)
	Close2.Font = Enum.Font.Code
	Close2.Text = "Run"
	Close2.TextColor3 = Color3.fromRGB(255, 255, 255)
	Close2.TextScaled = true
	Close2.TextSize = 14.000
	Close2.TextWrapped = true

	local Sep3 = Instance.new("Frame")
	Sep3.Name = "Sep"
	Sep3.Parent = Content
	Sep3.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	Sep3.BorderColor3 = Color3.fromRGB(0, 0, 0)
	Sep3.BorderSizePixel = 0
	Sep3.Size = UDim2.new(0.00318877562, 0, 1, 0)
	Sep3.BorderSizePixel = 0
    
	local Arguments = Instance.new("ScrollingFrame")
	Arguments.Name = "Arguments"
	Arguments.Parent = Content
	Arguments.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	Arguments.BackgroundTransparency = 1.000
	Arguments.BorderColor3 = Color3.fromRGB(0, 0, 0)
	Arguments.BorderSizePixel = 0
	Arguments.Selectable = false
	Arguments.CanvasSize = UDim2.new(0, 0, 0, 0)
	Arguments.Size = UDim2.new(1, 0, 0.899999976, 0)
	Arguments.ScrollBarThickness = 6

	local DescriptionLabel = Instance.new("TextLabel")
	DescriptionLabel.Name = "DescriptionLabel"
	DescriptionLabel.Text = ""
	DescriptionLabel.Parent = Arguments
	DescriptionLabel.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	DescriptionLabel.BackgroundTransparency = 1.000
	DescriptionLabel.BorderColor3 = Color3.fromRGB(0, 0, 0)
	DescriptionLabel.BorderSizePixel = 0
	DescriptionLabel.Size = UDim2.new(1, 0, 0.150000006, 0)
	DescriptionLabel.Font = Enum.Font.Code
	DescriptionLabel.TextColor3 = Color3.fromRGB(255, 255, 255)
	DescriptionLabel.TextScaled = true
	DescriptionLabel.TextSize = 14.000
	DescriptionLabel.TextWrapped = true
	DescriptionLabel.TextXAlignment = Enum.TextXAlignment.Left

	local UIPadding = Instance.new("UIPadding")
	UIPadding.Parent = DescriptionLabel
	UIPadding.PaddingBottom = UDim.new(0, 10)
	UIPadding.PaddingLeft = UDim.new(0, 10)
	UIPadding.PaddingRight = UDim.new(0, 10)
	UIPadding.PaddingTop = UDim.new(0, 10)

	local ArgumentSample = Instance.new("Frame")
	ArgumentSample.Name = "ArgumentSample"
	ArgumentSample.Parent = Arguments
	ArgumentSample.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	ArgumentSample.BackgroundTransparency = 1.000
	ArgumentSample.BorderColor3 = Color3.fromRGB(0, 0, 0)
	ArgumentSample.BorderSizePixel = 0
	ArgumentSample.Visible = false
	ArgumentSample.Size = UDim2.new(1, 0, 0.150000006, 0)

	local UIPadding10 = Instance.new("UIPadding")
	UIPadding10.Parent = ArgumentSample
	UIPadding10.PaddingBottom = UDim.new(0, 10)
	UIPadding10.PaddingLeft = UDim.new(0, 10)
	UIPadding10.PaddingRight = UDim.new(0, 10)
	UIPadding10.PaddingTop = UDim.new(0, 10)
	
	local NameLabel = Instance.new("TextLabel")
	NameLabel.Name = "NameLabel"
	NameLabel.Parent = ArgumentSample
	NameLabel.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	NameLabel.BackgroundTransparency = 1.000
	NameLabel.BorderColor3 = Color3.fromRGB(0, 0, 0)
	NameLabel.BorderSizePixel = 0
	NameLabel.Size = UDim2.new(0.5, 0, 0.5, 0)
	NameLabel.Font = Enum.Font.Code
	NameLabel.TextColor3 = Color3.fromRGB(255, 255, 255)
	NameLabel.TextScaled = true
	NameLabel.TextSize = 14.000
	NameLabel.TextWrapped = true
	NameLabel.TextXAlignment = Enum.TextXAlignment.Left

	local DescLabel = Instance.new("TextLabel")
	DescLabel.Name = "DescLabel"
	DescLabel.Parent = ArgumentSample
	DescLabel.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	DescLabel.BackgroundTransparency = 1.000
	DescLabel.BorderColor3 = Color3.fromRGB(0, 0, 0)
	DescLabel.BorderSizePixel = 0
	DescLabel.Position = UDim2.new(0, 0, 0.5, 0)
	DescLabel.Size = UDim2.new(0.5, 0, 0.5, 0)
	DescLabel.Font = Enum.Font.Code
	DescLabel.TextColor3 = Color3.fromRGB(255, 255, 255)
	DescLabel.TextScaled = true
	DescLabel.TextSize = 14.000
	DescLabel.TextWrapped = true
	DescLabel.TextXAlignment = Enum.TextXAlignment.Left

	local Menu = Instance.new("TextButton")
	Menu.Name = "Menu"
	Menu.Parent = ArgumentSample
	Menu.AnchorPoint = Vector2.new(1, 0.5)
	Menu.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
	Menu.BackgroundTransparency = 0.500
	Menu.BorderColor3 = Color3.fromRGB(0, 0, 0)
	Menu.BorderSizePixel = 0
	Menu.Position = UDim2.new(1, 0, 0.5, 0)
	Menu.Size = UDim2.new(0.150000006, 0, 0.800000012, 0)
	Menu.Font = Enum.Font.Code
	Menu.Text = ""
	Menu.TextColor3 = Color3.fromRGB(255, 255, 255)
	Menu.TextScaled = true
	Menu.TextSize = 14.000
	Menu.TextWrapped = true
	Menu.AutomaticSize = Enum.AutomaticSize.X

	local UIPaddingM = Instance.new("UIPadding")
	UIPaddingM.Parent = Menu
	UIPaddingM.PaddingBottom = UDim.new(0, 10)
	UIPaddingM.PaddingLeft = UDim.new(0, 10)
	UIPaddingM.PaddingRight = UDim.new(0, 10)
	UIPaddingM.PaddingTop = UDim.new(0, 10)

	local Input = Instance.new("TextBox")
	Input.Name = "Input"
	Input.Parent = ArgumentSample
	Input.AnchorPoint = Vector2.new(1, 0.5)
	Input.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
	Input.BackgroundTransparency = 0.500
	Input.BorderColor3 = Color3.fromRGB(0, 0, 0)
	Input.BorderSizePixel = 0
	Input.Position = UDim2.new(1, 0, 0.5, 0)
	Input.Size = UDim2.new(0.5, 0, 0.800000012, 0)
	Input.Font = Enum.Font.Code
	Input.Text = ""
	Input.Visible = false
	Input.TextColor3 = Color3.fromRGB(255, 255, 255)
	Input.TextScaled = true
	Input.TextXAlignment = Enum.TextXAlignment.Left
	Input.TextSize = 14.000
	Input.TextWrapped = true
	Input.ClearTextOnFocus = false

	local UIPadding2 = Instance.new("UIPadding")
	UIPadding2.Parent = Input
	UIPadding2.PaddingBottom = UDim.new(0, 10)
	UIPadding2.PaddingLeft = UDim.new(0, 10)
	UIPadding2.PaddingRight = UDim.new(0, 10)
	UIPadding2.PaddingTop = UDim.new(0, 10)

	local UIListLayout2 = Instance.new("UIListLayout")
	UIListLayout2.Parent = Arguments
	UIListLayout2.SortOrder = Enum.SortOrder.LayoutOrder

	local DropMenu = Instance.new("Frame")
	DropMenu.Name = "DropMenu"
	DropMenu.Parent = Parent
	DropMenu.AnchorPoint = Vector2.new(1, 0)
	DropMenu.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
	DropMenu.BackgroundTransparency = 0.400
	DropMenu.BorderColor3 = Color3.fromRGB(0, 0, 0)
	DropMenu.BorderSizePixel = 0
	DropMenu.Position = UDim2.new(0.988520443, 0, 0.108680114, 0)
	DropMenu.Size = UDim2.new(0.2, 0, 0.195, 0)
	DropMenu.Visible = false

	local TextBox = Instance.new("TextBox")
	TextBox.Parent = DropMenu
	TextBox.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	TextBox.BackgroundTransparency = 0.900
	TextBox.BorderColor3 = Color3.fromRGB(0, 0, 0)
	TextBox.BorderSizePixel = 0
	TextBox.Size = UDim2.new(1, 0, 0.190666854, 0)
	TextBox.Font = Enum.Font.Code
	TextBox.PlaceholderText = "Search"
	TextBox.Text = ""
	TextBox.TextColor3 = Color3.fromRGB(255, 255, 255)
	TextBox.TextScaled = true
	TextBox.TextSize = 14.000
	TextBox.TextWrapped = true

	local UIPadding3 = Instance.new("UIPadding")
	UIPadding3.Parent = TextBox
	UIPadding3.PaddingBottom = UDim.new(0, 10)
	UIPadding3.PaddingLeft = UDim.new(0, 10)
	UIPadding3.PaddingRight = UDim.new(0, 10)
	UIPadding3.PaddingTop = UDim.new(0, 10)

	local ScrollingFrame = Instance.new("ScrollingFrame")
	ScrollingFrame.Parent = DropMenu
	ScrollingFrame.Active = true
	ScrollingFrame.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	ScrollingFrame.BackgroundTransparency = 1.000
	ScrollingFrame.BorderColor3 = Color3.fromRGB(0, 0, 0)
	ScrollingFrame.BorderSizePixel = 0
	ScrollingFrame.Position = UDim2.new(0, 0, 0.191, 0)
	ScrollingFrame.Size = UDim2.new(1, 0, 0.809000015, 0)
	ScrollingFrame.CanvasSize = UDim2.new(0, 0, 0, 0)
	ScrollingFrame.ScrollBarThickness = 6

	local DropButton = Instance.new("TextButton")
	DropButton.Name = "DropButton"
	DropButton.Parent = ScrollingFrame
	DropButton.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	DropButton.BackgroundTransparency = 1.000
	DropButton.BorderColor3 = Color3.fromRGB(0, 0, 0)
	DropButton.BorderSizePixel = 0
	DropButton.Size = UDim2.new(1, 0, 0.200000003, 0)
	DropButton.Font = Enum.Font.Code
	DropButton.TextColor3 = Color3.fromRGB(255, 255, 255)
	DropButton.TextScaled = true
	DropButton.TextSize = 14.000
	DropButton.TextWrapped = true
	DropButton.Visible = false

	local UIListLayout_3 = Instance.new("UIListLayout")
	UIListLayout_3.Parent = ScrollingFrame
	UIListLayout_3.SortOrder = Enum.SortOrder.LayoutOrder

	local Detect = Instance.new("Frame")
	Detect.Name = "Detect"
	Detect.Parent = Parent
	Detect.Active = true
	Detect.Visible = false
	Detect.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	Detect.BackgroundTransparency = 1.000
	Detect.BorderColor3 = Color3.fromRGB(0, 0, 0)
	Detect.BorderSizePixel = 0
	Detect.Size = UDim2.new(1, 0, 1, 0)

	local InfoLabel = Instance.new("TextLabel")
	InfoLabel.Name = "InfoLabel"
	InfoLabel.Parent = Content
	InfoLabel.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
	InfoLabel.BackgroundTransparency = 0.300
	InfoLabel.BorderColor3 = Color3.fromRGB(0, 0, 0)
	InfoLabel.BorderSizePixel = 0
	InfoLabel.Size = UDim2.new(1, 0, 1, 0)
	InfoLabel.Font = Enum.Font.Code
	InfoLabel.TextColor3 = Color3.fromRGB(255, 255, 255)
	InfoLabel.TextScaled = true
	InfoLabel.TextSize = 14.000
	InfoLabel.TextWrapped = true
	InfoLabel.Visible = false
end
