blank_issues_enabled: true
contact_links:
  - name: Discord Server
    url: https://discord.gg/g5PdMxh
    about: Please us the cmdr-help channel if you need support
  - name: Security Policy
    url: https://github.com/evaera/Cmdr/security/policy
    about: Do not report security issues on GitHub. Our policy details how you should alert us to vulnerabilities.
