name: Feature request
description: Please use this form to make a suggestion or request a new feature for Cmdr
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to contribute to Cmdr. Please aim to fill this form out in as much detail as possible to help us best address your needs.
  - type: textarea
    id: feature
    attributes:
      label: What feature are you requesting?
      description: What should be added to the Cmdr library and why? Focus less on proposing a specific implementation and more on what you need.
      placeholder: Please try to write this in a narrative format. For example, "it's currently too hard to do X".
    validations:
      required: true
  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: What part of Cmdr does this feature request relate to?
      options:
        - Built-in command
        - Built-in type
        - Interface
        - Core or internal (including the Util module and Cmdr server and client singletons)
        - Website or documentation
        - Something else
        - I'm not sure
    validations:
      required: true
  - type: textarea
    id: anything-else
    attributes:
      label: Anything else?
      description: Please include any other details, if applicable, which you think are important.
